"""empty message

Revision ID: 112236ec90d0
Revises: 7f4bb17dcd79
Create Date: 2018-03-02 00:01:29.334175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112236ec90d0'
down_revision = '7f4bb17dcd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    # ### end Alembic commands ###
