language: python
python:
  - "3.6"
env:
  global:
    - ENV_TYPE='TESTING'
    - DATABASE_URL_TESTING='postgresql+psycopg2://postgres:@localhost:5432/flaskmt_test'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libenchant-dev
install:
  - pip install -r app/requirements/test.txt
services:
  - postgresql
before_script:
  - psql -c 'create database flaskmt_test;' -U postgres
script:
  - python app/tests.py
