language: python
python:
  - "3.6"
install:
  - pip install -r app/requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python app/tests.py
