#!/bin/env bash
psql -U postgres -c "CREATE USER $DB_USER PASSWORD '$DB_PASS'"
psql -U postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USER"

# Testing DB
psql -U postgres -c "CREATE USER $DB_USER_TESTING PASSWORD '$DB_PASS_TESTING'"
psql -U postgres -c "CREATE DATABASE $DB_NAME_TESTING OWNER $DB_USER_TESTING"
